dist: xenial

language: python

python:
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - yamllint .
  - python -m py_compile configure_devices.py
  - python -m py_compile collect_commands.py
  - python -m py_compile parse_junos_command.py
  - python -m py_compile validate_bgp_sessions_state.py
  - python -m py_compile netmiko_and_ntc_textfsm_templates.py

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
    on_success: never
